Output demo.gif

Set FontSize 24
Set Width 1200
Set Height 600

Type "regex-tui"
Sleep 1s
Enter
Sleep 1s
Backspace 3
Sleep 1s
Backspace 5
Sleep 1s
Type "\w"
Sleep 1s
Type "+"
Sleep 2s
Tab
Ctrl+W
Sleep 500ms
Ctrl+W
Sleep 1s
Type "Regex TUI is a simple tool to test and visualize Regular Expressions."
Enter
Type "Created by Vitor Mariano"
Tab
Sleep 3s
Backspace 3
Sleep 1s
Type "[A-Z]"
Sleep 1s
Type "\w"
Sleep 1s
Type "+"
Sleep 4s
